# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmmain.ui'
#
# Created: Mon Nov 17 01:35:33 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import ext_stuffs
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmmain(object):
    def setupUi(self, frmmain):
        frmmain.setObjectName(_fromUtf8("frmmain"))
        frmmain.resize(694, 466)
        frmmain.setStatusTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(frmmain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.txtterminal = QtGui.QTextEdit(self.centralwidget)
        self.txtterminal.setGeometry(QtCore.QRect(160, 10, 281, 91))
        self.txtterminal.setUndoRedoEnabled(False)
        self.txtterminal.setReadOnly(True)
        self.txtterminal.setObjectName(_fromUtf8("txtterminal"))
        self.grpterminal = QtGui.QGroupBox(self.centralwidget)
        self.grpterminal.setGeometry(QtCore.QRect(10, 10, 141, 91))
        self.grpterminal.setTitle(_fromUtf8(""))
        self.grpterminal.setObjectName(_fromUtf8("grpterminal"))
        self.bttnterminal = QtGui.QPushButton(self.grpterminal)
        self.bttnterminal.setGeometry(QtCore.QRect(0, 0, 141, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../home/shovon/Desktop/python stuffs/gui/Terminal-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bttnterminal.setIcon(icon)
        self.bttnterminal.setObjectName(_fromUtf8("bttnterminal"))
        self.rdoprgfolder = QtGui.QRadioButton(self.grpterminal)
        self.rdoprgfolder.setGeometry(QtCore.QRect(0, 50, 116, 22))
        self.rdoprgfolder.setObjectName(_fromUtf8("rdoprgfolder"))
        self.rdohexfolder = QtGui.QRadioButton(self.grpterminal)
        self.rdohexfolder.setGeometry(QtCore.QRect(0, 70, 116, 22))
        self.rdohexfolder.setChecked(True)
        self.rdohexfolder.setObjectName(_fromUtf8("rdohexfolder"))
        self.grpprgset = QtGui.QGroupBox(self.centralwidget)
        self.grpprgset.setGeometry(QtCore.QRect(450, 10, 211, 91))
        self.grpprgset.setObjectName(_fromUtf8("grpprgset"))
        self.label_4 = QtGui.QLabel(self.grpprgset)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 81, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.grpprgset)
        self.label_5.setGeometry(QtCore.QRect(0, 50, 81, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cboport = QtGui.QComboBox(self.grpprgset)
        self.cboport.setGeometry(QtCore.QRect(80, 20, 91, 27))
        self.cboport.setObjectName(_fromUtf8("cboport"))
        self.cbobaudrate = QtGui.QLineEdit(self.grpprgset)
        self.cbobaudrate.setGeometry(QtCore.QRect(80, 50, 121, 27))
        self.cbobaudrate.setObjectName(_fromUtf8("cbobaudrate"))
        self.bttnrefreshports = QtGui.QPushButton(self.grpprgset)
        self.bttnrefreshports.setGeometry(QtCore.QRect(170, 20, 30, 26))
        self.bttnrefreshports.setObjectName(_fromUtf8("bttnrefreshports"))
        self.lblnote1 = QtGui.QLabel(self.centralwidget)
        self.lblnote1.setGeometry(QtCore.QRect(450, 110, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblnote1.setFont(font)
        self.lblnote1.setObjectName(_fromUtf8("lblnote1"))
        self.lblprg = QtGui.QLabel(self.centralwidget)
        self.lblprg.setGeometry(QtCore.QRect(10, 420, 341, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblprg.sizePolicy().hasHeightForWidth())
        self.lblprg.setSizePolicy(sizePolicy)
        self.lblprg.setText(_fromUtf8(""))
        self.lblprg.setObjectName(_fromUtf8("lblprg"))
        self.grpfile = QtGui.QGroupBox(self.centralwidget)
        self.grpfile.setGeometry(QtCore.QRect(20, 120, 381, 81))
        self.grpfile.setFlat(False)
        self.grpfile.setObjectName(_fromUtf8("grpfile"))
        self.bttnbrowse = QtGui.QPushButton(self.grpfile)
        self.bttnbrowse.setGeometry(QtCore.QRect(0, 20, 71, 51))
        self.bttnbrowse.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../home/shovon/Desktop/python stuffs/gui/Open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bttnbrowse.setIcon(icon1)
        self.bttnbrowse.setIconSize(QtCore.QSize(32, 32))
        self.bttnbrowse.setObjectName(_fromUtf8("bttnbrowse"))
        self.txtfilename = QtGui.QLineEdit(self.grpfile)
        self.txtfilename.setGeometry(QtCore.QRect(80, 20, 291, 27))
        self.txtfilename.setObjectName(_fromUtf8("txtfilename"))
        self.rdoflash = QtGui.QRadioButton(self.grpfile)
        self.rdoflash.setGeometry(QtCore.QRect(80, 50, 71, 22))
        self.rdoflash.setChecked(True)
        self.rdoflash.setObjectName(_fromUtf8("rdoflash"))
        self.rdoeeprom = QtGui.QRadioButton(self.grpfile)
        self.rdoeeprom.setGeometry(QtCore.QRect(150, 50, 91, 22))
        self.rdoeeprom.setObjectName(_fromUtf8("rdoeeprom"))
        self.bttnwrite = QtGui.QPushButton(self.centralwidget)
        self.bttnwrite.setGeometry(QtCore.QRect(20, 200, 121, 61))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../home/shovon/Desktop/python stuffs/gui/write.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bttnwrite.setIcon(icon2)
        self.bttnwrite.setIconSize(QtCore.QSize(32, 32))
        self.bttnwrite.setObjectName(_fromUtf8("bttnwrite"))
        self.bttnread = QtGui.QPushButton(self.centralwidget)
        self.bttnread.setGeometry(QtCore.QRect(140, 200, 111, 61))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../home/shovon/Desktop/python stuffs/gui/book-open-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bttnread.setIcon(icon3)
        self.bttnread.setIconSize(QtCore.QSize(32, 32))
        self.bttnread.setObjectName(_fromUtf8("bttnread"))
        self.bttnverify = QtGui.QPushButton(self.centralwidget)
        self.bttnverify.setGeometry(QtCore.QRect(20, 270, 121, 61))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../home/shovon/Desktop/python stuffs/gui/Check-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bttnverify.setIcon(icon4)
        self.bttnverify.setIconSize(QtCore.QSize(32, 32))
        self.bttnverify.setObjectName(_fromUtf8("bttnverify"))
        self.gpcs_chip = ext_stuffs.ExtendedQLabel(self.centralwidget)
        self.gpcs_chip.setGeometry(QtCore.QRect(260, 200, 151, 151))
        self.gpcs_chip.setText(_fromUtf8(""))
        self.gpcs_chip.setPixmap(QtGui.QPixmap(_fromUtf8("../home/shovon/Desktop/python stuffs/gui/chipimage.png")))
        self.gpcs_chip.setAlignment(QtCore.Qt.AlignCenter)
        self.gpcs_chip.setObjectName(_fromUtf8("gpcs_chip"))
        self.bttnerase = QtGui.QPushButton(self.centralwidget)
        self.bttnerase.setGeometry(QtCore.QRect(140, 270, 111, 61))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../home/shovon/Desktop/python stuffs/gui/1414641771_DeleteRed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bttnerase.setIcon(icon5)
        self.bttnerase.setObjectName(_fromUtf8("bttnerase"))
        self.chksetsck = QtGui.QCheckBox(self.centralwidget)
        self.chksetsck.setGeometry(QtCore.QRect(20, 340, 211, 22))
        self.chksetsck.setObjectName(_fromUtf8("chksetsck"))
        self.grpfuse = QtGui.QGroupBox(self.centralwidget)
        self.grpfuse.setGeometry(QtCore.QRect(440, 200, 241, 201))
        self.grpfuse.setObjectName(_fromUtf8("grpfuse"))
        self.lblpredef = QtGui.QLabel(self.grpfuse)
        self.lblpredef.setGeometry(QtCore.QRect(10, 20, 141, 17))
        self.lblpredef.setObjectName(_fromUtf8("lblpredef"))
        self.label = QtGui.QLabel(self.grpfuse)
        self.label.setGeometry(QtCore.QRect(10, 70, 41, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.grpfuse)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 41, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.grpfuse)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 41, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cbopredefs = QtGui.QComboBox(self.grpfuse)
        self.cbopredefs.setGeometry(QtCore.QRect(10, 40, 221, 27))
        self.cbopredefs.setObjectName(_fromUtf8("cbopredefs"))
        self.txthfuse = QtGui.QLineEdit(self.grpfuse)
        self.txthfuse.setGeometry(QtCore.QRect(60, 70, 51, 21))
        self.txthfuse.setObjectName(_fromUtf8("txthfuse"))
        self.txtlfuse = QtGui.QLineEdit(self.grpfuse)
        self.txtlfuse.setGeometry(QtCore.QRect(60, 100, 51, 21))
        self.txtlfuse.setObjectName(_fromUtf8("txtlfuse"))
        self.txtefuse = QtGui.QLineEdit(self.grpfuse)
        self.txtefuse.setGeometry(QtCore.QRect(60, 130, 51, 21))
        self.txtefuse.setObjectName(_fromUtf8("txtefuse"))
        self.bttnclock = QtGui.QPushButton(self.grpfuse)
        self.bttnclock.setGeometry(QtCore.QRect(120, 70, 111, 27))
        self.bttnclock.setObjectName(_fromUtf8("bttnclock"))
        self.bttnadvanced = QtGui.QPushButton(self.grpfuse)
        self.bttnadvanced.setGeometry(QtCore.QRect(120, 100, 111, 27))
        self.bttnadvanced.setObjectName(_fromUtf8("bttnadvanced"))
        self.bttnwritefuse = QtGui.QPushButton(self.grpfuse)
        self.bttnwritefuse.setGeometry(QtCore.QRect(10, 170, 98, 27))
        self.bttnwritefuse.setObjectName(_fromUtf8("bttnwritefuse"))
        self.bttnreadfuse = QtGui.QPushButton(self.grpfuse)
        self.bttnreadfuse.setGeometry(QtCore.QRect(120, 170, 98, 27))
        self.bttnreadfuse.setObjectName(_fromUtf8("bttnreadfuse"))
        self.bttncalnlock = QtGui.QPushButton(self.grpfuse)
        self.bttncalnlock.setGeometry(QtCore.QRect(120, 130, 111, 27))
        self.bttncalnlock.setObjectName(_fromUtf8("bttncalnlock"))
        self.bttneeprom = QtGui.QPushButton(self.centralwidget)
        self.bttneeprom.setGeometry(QtCore.QRect(20, 370, 151, 31))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../home/shovon/Desktop/python stuffs/gui/writing_app.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bttneeprom.setIcon(icon6)
        self.bttneeprom.setObjectName(_fromUtf8("bttneeprom"))
        self.lblchipname = QtGui.QLabel(self.centralwidget)
        self.lblchipname.setGeometry(QtCore.QRect(280, 270, 111, 17))
        self.lblchipname.setStyleSheet(_fromUtf8("color: white"))
        self.lblchipname.setText(_fromUtf8(""))
        self.lblchipname.setTextFormat(QtCore.Qt.AutoText)
        self.lblchipname.setAlignment(QtCore.Qt.AlignCenter)
        self.lblchipname.setObjectName(_fromUtf8("lblchipname"))
        self.lblnote = QtGui.QLabel(self.centralwidget)
        self.lblnote.setGeometry(QtCore.QRect(260, 350, 151, 51))
        self.lblnote.setObjectName(_fromUtf8("lblnote"))
        self.lblstatus = QtGui.QLabel(self.centralwidget)
        self.lblstatus.setGeometry(QtCore.QRect(370, 420, 331, 17))
        self.lblstatus.setText(_fromUtf8(""))
        self.lblstatus.setObjectName(_fromUtf8("lblstatus"))
        frmmain.setCentralWidget(self.centralwidget)
        self.mnumenubar = QtGui.QMenuBar(frmmain)
        self.mnumenubar.setGeometry(QtCore.QRect(0, 0, 694, 23))
        self.mnumenubar.setStyleSheet(_fromUtf8(""))
        self.mnumenubar.setNativeMenuBar(False)
        self.mnumenubar.setObjectName(_fromUtf8("mnumenubar"))
        self.menuProgrammers_Boards = QtGui.QMenu(self.mnumenubar)
        self.menuProgrammers_Boards.setObjectName(_fromUtf8("menuProgrammers_Boards"))
        self.menuArduino_Boards = QtGui.QMenu(self.menuProgrammers_Boards)
        self.menuArduino_Boards.setObjectName(_fromUtf8("menuArduino_Boards"))
        self.menuOther_Custom = QtGui.QMenu(self.menuProgrammers_Boards)
        self.menuOther_Custom.setObjectName(_fromUtf8("menuOther_Custom"))
        self.menuAbout = QtGui.QMenu(self.mnumenubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        frmmain.setMenuBar(self.mnumenubar)
        self.actionUSBasp = QtGui.QAction(frmmain)
        self.actionUSBasp.setCheckable(False)
        self.actionUSBasp.setObjectName(_fromUtf8("actionUSBasp"))
        self.actionManage = QtGui.QAction(frmmain)
        self.actionManage.setObjectName(_fromUtf8("actionManage"))
        self.actionTest = QtGui.QAction(frmmain)
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.actionAVRisp = QtGui.QAction(frmmain)
        self.actionAVRisp.setObjectName(_fromUtf8("actionAVRisp_2"))
        self.actionA = QtGui.QAction(frmmain)
        self.actionA.setObjectName(_fromUtf8("actionA"))
        self.menuProgrammers_Boards.addAction(self.actionUSBasp)
        self.menuProgrammers_Boards.addAction(self.actionAVRisp)
        self.menuProgrammers_Boards.addAction(self.menuArduino_Boards.menuAction())
        self.menuProgrammers_Boards.addAction(self.menuOther_Custom.menuAction())
        self.menuProgrammers_Boards.addSeparator()
        self.menuProgrammers_Boards.addAction(self.actionManage)
        self.mnumenubar.addAction(self.menuProgrammers_Boards.menuAction())
        self.mnumenubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(frmmain)
        QtCore.QMetaObject.connectSlotsByName(frmmain)

    def retranslateUi(self, frmmain):
        frmmain.setWindowTitle(_translate("frmmain", "CEMSTech AVRxpal", None))
        self.txtterminal.setHtml(_translate("frmmain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\" bgcolor=\"#000000\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p></body></html>", None))
        self.bttnterminal.setText(_translate("frmmain", "Terminal/cmd...", None))
        self.rdoprgfolder.setText(_translate("frmmain", "in app dir.", None))
        self.rdohexfolder.setText(_translate("frmmain", "in hex dir.", None))
        self.grpprgset.setTitle(_translate("frmmain", "Serial Port Settings", None))
        self.label_4.setText(_translate("frmmain", "Select port:", None))
        self.label_5.setText(_translate("frmmain", "Baud            :", None))
        self.bttnrefreshports.setText(_translate("frmmain", "R", None))
        self.lblnote1.setText(_translate("frmmain", "Note:Above settings are only\n"
"for Arduino and serial port based\n"
"programmers.", None))
        self.grpfile.setTitle(_translate("frmmain", "Select file to load", None))
        self.rdoflash.setText(_translate("frmmain", "Flash", None))
        self.rdoeeprom.setText(_translate("frmmain", "EEPROM", None))
        self.bttnwrite.setText(_translate("frmmain", "Write", None))
        self.bttnread.setText(_translate("frmmain", "Read", None))
        self.bttnverify.setText(_translate("frmmain", "Verify", None))
        self.bttnerase.setText(_translate("frmmain", "Erase Chip", None))
        self.chksetsck.setText(_translate("frmmain", "Set slow SCK (USBasp only)", None))
        self.grpfuse.setTitle(_translate("frmmain", "Fuse Settings", None))
        self.lblpredef.setText(_translate("frmmain", "Saved Fuse Settings", None))
        self.label.setText(_translate("frmmain", "hfuse:", None))
        self.label_2.setText(_translate("frmmain", "lfuse:", None))
        self.label_3.setText(_translate("frmmain", "efuse:", None))
        self.bttnclock.setText(_translate("frmmain", "Clock Speed...", None))
        self.bttnadvanced.setText(_translate("frmmain", "Advanced...", None))
        self.bttnwritefuse.setText(_translate("frmmain", "Write Fuse", None))
        self.bttnreadfuse.setText(_translate("frmmain", "Read Fuse", None))
        self.bttncalnlock.setText(_translate("frmmain", "Cal. and Lock...", None))
        self.bttneeprom.setText(_translate("frmmain", "EEPROM Editor...", None))
        self.lblnote.setText(_translate("frmmain", "<html><head/><body><p>Click on the chip for</p><p>auto detection</p></body></html>", None))
        self.menuProgrammers_Boards.setTitle(_translate("frmmain", "Programmers/Boards", None))
        self.menuArduino_Boards.setTitle(_translate("frmmain", "Arduino Boards", None))
        self.menuOther_Custom.setTitle(_translate("frmmain", "Other/Custom", None))
        self.menuAbout.setTitle(_translate("frmmain", "About", None))
        self.actionUSBasp.setText(_translate("frmmain", "USBasp", None))
        self.actionManage.setText(_translate("frmmain", "Manage...", None))
        self.actionTest.setText(_translate("frmmain", "test", None))
        self.actionAVRisp.setText(_translate("frmmain", "AVRisp/ArduinoISP", None))
        self.actionA.setText(_translate("frmmain", "a", None))

